//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyTestApplicationEmber
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Computer type.
    /// </summary>
    //  *** Start programmer edit section *** (ComputerType CustomAttributes)

    //  *** End programmer edit section *** (ComputerType CustomAttributes)
    public enum ComputerType
    {
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (ComputerType.Unknown CustomAttributes)

        //  *** End programmer edit section *** (ComputerType.Unknown CustomAttributes)
        [Caption("")]
        Unknown,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (ComputerType.Desktop CustomAttributes)

        //  *** End programmer edit section *** (ComputerType.Desktop CustomAttributes)
        Desktop,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (ComputerType.Laptop CustomAttributes)

        //  *** End programmer edit section *** (ComputerType.Laptop CustomAttributes)
        Laptop,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (ComputerType.TabletPC CustomAttributes)

        //  *** End programmer edit section *** (ComputerType.TabletPC CustomAttributes)
        [Caption("Tablet PC")]
        TabletPC,
    }
}
