//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyTestApplicationEmber
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// I name.
    /// </summary>
    //  *** Start programmer edit section *** (IName CustomAttributes)

    //  *** End programmer edit section *** (IName CustomAttributes)
    public interface IName
    {
        
        //  *** Start programmer edit section *** (IName CustomMembers)

        //  *** End programmer edit section *** (IName CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Name CustomAttributes)

        //  *** End programmer edit section *** (Name CustomAttributes)
        string Name
        {
            get;
            set;
        }
    }
}
