//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyTestApplicationEmber
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// I name.
    /// </summary>
    //  *** Start programmer edit section *** (IName CustomAttributes)

    //  *** End programmer edit section *** (IName CustomAttributes)
    public interface IName
    {
        
        //  *** Start programmer edit section *** (IName CustomMembers)

        //  *** End programmer edit section *** (IName CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Name CustomAttributes)

        //  *** End programmer edit section *** (Name CustomAttributes)
        string Name
        {
            get;
            set;
        }
    }
}
