//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyTestApplicationEmber
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Computer BS.
    /// </summary>
    //  *** Start programmer edit section *** (ComputerBS CustomAttributes)

    //  *** End programmer edit section *** (ComputerBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ComputerBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        //  *** Start programmer edit section *** (ComputerBS CustomMembers)

        //  *** End programmer edit section *** (ComputerBS CustomMembers)

        
        //  *** Start programmer edit section *** (OnUpdateComputer CustomAttributes)

        //  *** End programmer edit section *** (OnUpdateComputer CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateComputer(IIS.MyTestApplicationEmber.Computer UpdatedObject)
        {
            //  *** Start programmer edit section *** (OnUpdateComputer)
            return new ICSSoft.STORMNET.DataObject[0];
            //  *** End programmer edit section *** (OnUpdateComputer)
        }
    }
}
